### ISSUE TITLE
Unnecessary save function override for RegisterForm

### ISSUE THREAD

**Issue by fluix-dev** [pnoj/site#19]
[This function](https://github.com/pnoj/site/blob/63299e873b1fb654667545222ce2b3157e78acd9/judge/forms.py#L27) seems to have a noop path and another path that's no different from the `UserCreationForm`'s method. There's two code paths:
#### `commit=False`
In this case, the `super()` form is called and saved, with the email being set to the `self.cleaned_data["email"]` which it would normally do anyways. The new object is never returned so it's lost forever, unlike the `UserCreationForm` which would at least return it.

#### `commit=True`
In this case, everything that happens with `commit=False` happens, except the new object is saved and returned.

---

Perhaps I'm misunderstanding something, but this function seems unnecessary.

**Comment by HillcrestEnigma** [comment]
Thanks for noticing this. That function is very unnecessary and I am not sure why I added them in the first place. :+1:

**Comment by HillcrestEnigma** [comment]
Resolved in commit 8d3d152, thanks!
