### ISSUE TITLE
After submitting, clicking "Refresh" creates a new submission

### ISSUE THREAD

**Issue by yaxollum** [pnoj/site#4]
![Screenshot from 2020-05-05 12-41-04](https://user-images.githubusercontent.com/46109467/81091806-b9828500-8ecd-11ea-9511-4e9667ee477b.png)

**Comment by HillcrestEnigma** [comment]
for clarification, which browser are you using?

**Comment by yaxollum** [comment]
Vivaldi 3.0.1874.33

**Comment by hexadecimalDinosaur** [comment]
I do not think this is reproducible, specifically when did you click refresh @yaxollum?

Tested on vivaldi-stable 3.0.1874.38-1 on Ubuntu 20.04

**Comment by yaxollum** [comment]
For some reason this issue has magically gone away!
